"""empty message

Revision ID: 3ee525695cc3
Revises: 98f091372efd
Create Date: 2020-05-09 01:21:42.674477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee525695cc3'
down_revision = '98f091372efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'artist_name')
    op.drop_column('Shows', 'artist_image_link')
    op.drop_column('Shows', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
